#!/usr/bin/env node

// modules
var exec  = require('child_process').exec,
    path = require('path'),
    fs = require('fs'),
    nservDir = process.env.HOME + '/.nserv';

// vars
var appPath = path.resolve(__dirname + '/../../'),
    configfile = nservDir + '/domains.json',
    pathSegments = appPath.split('/'),
    domain = pathSegments[pathSegments.length - 1];

exec("export GIT_WORK_TREE=" + appPath + " && git checkout -f", function(err, stdout){
  error(err, "Could not checkout git tree.");
  fs.readFile(configfile, function (err, data) {
    error(err, "Could not read config file.");
    var config = JSON.parse(data);
    var port = config[domain].port;
    exec("PORT=" + port + " forever restart " + appPath + "/server.js", function(err, stdout){
      error(err, "Could not restart server.");
      console.log(stdout);
      success("Application updated.");
    });
  });
});

function success(message){
  console.log("data:    " + message);
}

function error (err, message) {
  if (err) {
    console.log("data:    " + message);
    console.log("data:    " + err);
    process.exit();
  }
}